package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestPipelineFlagHonoursModeEnv: `generate go -pipeline` (and -script)
// without -mode runs the stages under the shell's SSQL_MODE, as the
// stdin form does — until 2026-10-09 the flag forms always ran typed,
// so SSQL_MODE=record produced a typed program.
func TestPipelineFlagHonoursModeEnv(t *testing.T) {
	bin := buildSSQLForTypedTest(t)
	data := filepath.Join(t.TempDir(), "d.csv")
	if err := os.WriteFile(data, []byte("id,name\n1,a\n2,b\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	pipeline := bin + " from csv " + data + " | " + bin + " limit 1 | " + bin + " to csv"
	for _, c := range []struct{ env, want string }{
		{"record", "Generated by ssql"},
		{"typed", "(typed mode)"},
		{"parallel", "(typed mode)"},
		{"", "(typed mode)"},
	} {
		cmd := exec.Command(bin, "generate", "go", "-pipeline", pipeline)
		cmd.Env = append(os.Environ(), "SSQL_MODE="+c.env, "SSQLGO=")
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("SSQL_MODE=%q: %v\n%s", c.env, err, out)
		}
		header := string(out)
		if len(header) > 400 {
			header = header[:400] // the "Generated by ssql …" banner
		}
		if !strings.Contains(header, c.want) {
			t.Errorf("SSQL_MODE=%q: header %q, want it to contain %q", c.env, header, c.want)
		}
		if c.env == "record" && strings.Contains(header, "typed mode") {
			t.Errorf("SSQL_MODE=record produced a typed program: %q", header)
		}
	}
	// An explicit -mode still wins over the environment.
	cmd := exec.Command(bin, "generate", "go", "-mode", "record", "-pipeline", pipeline)
	cmd.Env = append(os.Environ(), "SSQL_MODE=typed")
	out, err := cmd.CombinedOutput()
	if err != nil || strings.Contains(string(out[:min(len(out), 400)]), "typed mode") {
		t.Errorf("-mode record under SSQL_MODE=typed: %v\n%s", err, out)
	}
}
