package main

import (
	"os/exec"
	"strings"
	"testing"

	"github.com/rosscartlidge/ssql/v4/cmd/ssql/commands"
)

// TestShellInitIncludesAll confirms `ssql -shell-init` is a true superset: it
// embeds the completion script plus every const-script integration in the
// ShellIntegrations table verbatim. Together with the commands-package drift
// guard (every emitter must be in the table), a new integration can't ship
// without -shell-init enabling it.
func TestShellInitIncludesAll(t *testing.T) {
	bin := buildSSQLForTypedTest(t)
	out, err := exec.Command(bin, "-shell-init").Output()
	if err != nil {
		t.Fatalf("-shell-init: %v", err)
	}
	s := string(out)

	// The completion script (generated by autocli) must be present.
	if !strings.Contains(s, "complete -F") {
		t.Errorf("-shell-init missing the completion script (`complete -F`)")
	}
	// Every const-script integration must be embedded verbatim.
	for _, si := range commands.ShellIntegrations {
		if si.Script == "" {
			continue
		}
		if !strings.Contains(s, si.Script) {
			t.Errorf("-shell-init does not contain the %s script verbatim", si.Flag)
		}
	}
}

// TestBareSSQLListsShellInit confirms the bare-`ssql` hint recommends
// -shell-init and still lists every individual integration flag.
func TestBareSSQLListsShellInit(t *testing.T) {
	bin := buildSSQLForTypedTest(t)
	out, err := exec.Command(bin).CombinedOutput()
	if err != nil {
		t.Fatalf("bare ssql: %v\n%s", err, out)
	}
	s := string(out)
	if !strings.Contains(s, "-shell-init") {
		t.Error("bare `ssql` hint does not recommend -shell-init")
	}
	for _, si := range commands.ShellIntegrations {
		if !strings.Contains(s, si.Flag) {
			t.Errorf("bare `ssql` hint does not list %s", si.Flag)
		}
	}
}
