package lib

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/rosscartlidge/ssql/v4/cmd/ssql/version"
)

// isTypedPipeline reports whether any fragment carries Phase 2 typed
// schema info — the marker we use to dispatch to the typed assembler.
// We tolerate a few stray non-typed fragments (e.g. an existing
// passthrough) by checking init/stmt/final fragments only.
func isTypedPipeline(fragments []*CodeFragment) bool {
	for _, f := range fragments {
		if f == nil {
			continue
		}
		if f.OutputTypedSchema != nil || f.InputTypedSchema != nil {
			return true
		}
	}
	return false
}

// assembleTypedFragments builds a complete Go program from typed-mode
// fragments. Differences vs the Record assembler:
//
//   - Imports github.com/rosscartlidge/ssql/v4/typed instead of v4
//   - Emits collected StructDefs at the top of the file
//   - Each stmt fragment's code is a complete typed.X[T] call already,
//     so we don't try to compose them via ssql.Chain (whose generic
//     parameters wouldn't match across stages)
//   - Errors out if any non-init/stmt/final fragment slips through
//   - Errors out if fragments are missing typed schema info partway
//     through (mixed-mode is unsupported)
func assembleTypedFragments(fragments []*CodeFragment) (string, error) {
	// Run the typed-mode planner first. It walks the fragment list and
	// returns:
	//   - which fragments need a Stream.Serial() boundary inserted
	//     before them (SerialOnly fragments downstream of a Stream
	//     producer)
	//   - whether the source should emit a parallel primitive (not
	//     yet wired — Phase A.2 deferred)
	//
	// Boundary fragments are spliced into the fragment list before the
	// renderer walks them, so the rest of the assembler logic doesn't
	// need to know.
	fragments = applyPlannerBoundaries(fragments)

	var initFragments []*CodeFragment
	var stmtFragments []*CodeFragment
	var finalFragments []*CodeFragment
	var funcFragments []*CodeFragment

	for _, frag := range fragments {
		switch frag.Type {
		case "init":
			initFragments = append(initFragments, frag)
		case "stmt":
			stmtFragments = append(stmtFragments, frag)
		case "final":
			finalFragments = append(finalFragments, frag)
		case "func":
			funcFragments = append(funcFragments, frag)
		}
	}

	if len(initFragments) == 0 {
		return "", fmt.Errorf("typed assembler: no source fragment (need 'from FILE.csv' as the first stage)")
	}

	// Strict-mode check: every init/stmt fragment must carry typed
	// schema info. If a fragment slipped through without it, that
	// command does not yet support typed-mode emission. Surface a
	// clear error rather than producing broken Go.
	for _, f := range initFragments {
		if f.OutputTypedSchema == nil {
			return "", fmt.Errorf("ssql generate go -typed: init fragment from %q has no typed schema (command does not yet support typed mode)", f.Command)
		}
	}
	for _, f := range stmtFragments {
		if f.OutputTypedSchema == nil {
			return "", fmt.Errorf("ssql generate go -typed: command %q does not yet support typed mode (Tier 2 or Tier 3); drop -typed or refactor the pipeline", f.Command)
		}
	}
	for _, f := range finalFragments {
		if f.InputTypedSchema == nil {
			return "", fmt.Errorf("ssql generate go -typed: sink %q does not yet support typed mode", f.Command)
		}
	}

	// Collect parameters and imports.
	allParams := collectParams(fragments)
	importSet := make(map[string]bool)
	importSet["github.com/rosscartlidge/ssql/v4/typed"] = true
	if len(allParams) > 0 {
		importSet["flag"] = true
	}
	if len(funcFragments) > 0 {
		importSet["iter"] = true
	}
	if len(finalFragments) == 0 {
		// Fall back to JSONL output via typed.WriteJSONLToWriter.
		importSet["fmt"] = true
		importSet["os"] = true
	}
	for _, frag := range fragments {
		for _, imp := range frag.Imports {
			if imp != "" {
				importSet[imp] = true
			}
		}
		for _, body := range frag.FuncBody {
			for _, imp := range body.Imports {
				if imp != "" {
					importSet[imp] = true
				}
			}
		}
	}
	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	sortImports(imports)

	// Collect and dedupe struct definitions.
	structDefs := collectTypedStructs(fragments)

	var code strings.Builder
	code.WriteString("package main\n\n")

	// Pipeline comment.
	var commands []string
	for _, frag := range fragments {
		if frag.Type == "func" {
			continue
		}
		if frag.Command != "" {
			commands = append(commands, frag.Command)
		}
	}
	if len(commands) > 0 {
		code.WriteString("/*\n")
		fmt.Fprintf(&code, "Generated by ssql %s (typed mode):\n\n", version.Version)
		code.WriteString("(export SSQLGO=typed\n")
		for _, cmd := range commands {
			code.WriteString(cmd + " |\n")
		}
		code.WriteString("ssql generate go)\n")
		code.WriteString("*/\n\n")
	}

	// Imports.
	if len(imports) > 0 {
		code.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&code, "\t%q\n", imp)
		}
		code.WriteString(")\n\n")
	}

	// Struct definitions.
	for _, def := range structDefs {
		code.WriteString(def)
		if !strings.HasSuffix(def, "\n") {
			code.WriteString("\n")
		}
		code.WriteString("\n")
	}

	// Subprocess functions (process substitution).
	for _, ff := range funcFragments {
		code.WriteString(generateTypedSubprocessFunction(ff))
		code.WriteString("\n")
	}

	// Flag declarations.
	if len(allParams) > 0 {
		code.WriteString("var (\n")
		for _, p := range allParams {
			if p.Type == "int" {
				fmt.Fprintf(&code, "\t%s = flag.Int(%q, %s, %q)\n", p.VarName, p.Name, p.Default, p.Help)
			} else {
				fmt.Fprintf(&code, "\t%s = flag.String(%q, %q, %q)\n", p.VarName, p.Name, p.Default, p.Help)
			}
		}
		code.WriteString(")\n\n")
	}

	code.WriteString("func main() {\n")
	if len(allParams) > 0 {
		code.WriteString("\tflag.Parse()\n\n")
	}

	// init fragments — emit code as-is (they include `records := typed.ReadCSV[T]...`)
	for _, frag := range initFragments {
		code.WriteString("\t" + frag.Code + "\n")
	}

	// stmt fragments — each is a complete typed.X assignment chained from
	// the previous variable. Emit verbatim.
	for _, frag := range stmtFragments {
		code.WriteString("\t" + frag.Code + "\n")
	}

	// final fragments — sinks.
	if len(finalFragments) > 0 {
		for _, frag := range finalFragments {
			code.WriteString("\t" + frag.Code + "\n")
		}
	} else {
		// No sink — emit JSONL fallback to stdout.
		var outVar string
		if len(stmtFragments) > 0 {
			outVar = stmtFragments[len(stmtFragments)-1].Var
		} else {
			outVar = initFragments[0].Var
		}
		code.WriteString("\t// No sink in pipeline — emit JSONL to stdout\n")
		fmt.Fprintf(&code, "\tif err := typed.WriteJSONLToWriter(%s, os.Stdout); err != nil {\n", outVar)
		code.WriteString("\t\tfmt.Fprintf(os.Stderr, \"write: %v\\n\", err)\n")
		code.WriteString("\t\tos.Exit(1)\n")
		code.WriteString("\t}\n")
	}

	code.WriteString("}\n")
	return code.String(), nil
}

// collectTypedStructs gathers and dedupes StructDefs from every
// fragment, preserving insertion order so referenced types appear
// before referring ones (since each fragment lists its own definitions
// in the order they're declared).
func collectTypedStructs(fragments []*CodeFragment) []string {
	seen := make(map[string]bool)
	var out []string
	for _, frag := range fragments {
		for _, def := range frag.StructDefs {
			key := strings.TrimSpace(def)
			if seen[key] {
				continue
			}
			seen[key] = true
			out = append(out, def)
		}
		for _, body := range frag.FuncBody {
			for _, def := range body.StructDefs {
				key := strings.TrimSpace(def)
				if seen[key] {
					continue
				}
				seen[key] = true
				out = append(out, def)
			}
		}
	}
	return out
}

// generateTypedSubprocessFunction emits a `func name() iter.Seq[T]`
// for a process-sub source, mirroring generateSubprocessFunction but
// with typed-mode return types derived from the func body's
// OutputTypedSchema.
func generateTypedSubprocessFunction(funcFrag *CodeFragment) string {
	var b strings.Builder
	if funcFrag.Command != "" {
		fmt.Fprintf(&b, "// %s\n", funcFrag.Command)
	}

	// Find the body's output type from the last init/stmt fragment.
	var typeName string
	for i := len(funcFrag.FuncBody) - 1; i >= 0; i-- {
		f := funcFrag.FuncBody[i]
		if f.OutputTypedSchema != nil {
			typeName = f.OutputTypedSchema.TypeName
			break
		}
	}
	if typeName == "" {
		typeName = "any"
	}

	fmt.Fprintf(&b, "func %s() iter.Seq[%s] {\n", funcFrag.FuncName, typeName)

	var initFrags, stmtFrags []*CodeFragment
	for _, f := range funcFrag.FuncBody {
		switch f.Type {
		case "init":
			initFrags = append(initFrags, f)
		case "stmt":
			stmtFrags = append(stmtFrags, f)
		}
	}
	for _, f := range initFrags {
		b.WriteString("\t" + f.Code + "\n")
	}
	for _, f := range stmtFrags {
		b.WriteString("\t" + f.Code + "\n")
	}

	// Return the last variable.
	var lastVar string
	if len(stmtFrags) > 0 {
		lastVar = stmtFrags[len(stmtFrags)-1].Var
	} else if len(initFrags) > 0 {
		lastVar = initFrags[0].Var
	}
	if lastVar != "" {
		fmt.Fprintf(&b, "\treturn %s\n", lastVar)
	}
	b.WriteString("}\n")
	return b.String()
}

// applyPlannerBoundaries runs the typed-mode planner over the
// fragment list and splices Stream.Serial() boundary fragments in
// where needed. The returned slice is the fragment list as it
// should be rendered.
//
// Boundary fragments are minimal stmt fragments that emit
// `<inputVar>Serial := <inputVar>.Serial()` and update the
// downstream fragment's Input to point at the new var. Capabilities
// are set so subsequent planner runs (idempotent) wouldn't
// re-insert.
func applyPlannerBoundaries(fragments []*CodeFragment) []*CodeFragment {
	plan := MakePlan(fragments)
	if len(plan.SerialBoundaryBefore) == 0 {
		return fragments
	}
	out := make([]*CodeFragment, 0, len(fragments)+len(plan.SerialBoundaryBefore))
	for i, f := range fragments {
		if plan.SerialBoundaryBefore[i] {
			// The fragment at index i is SerialOnly and its upstream
			// produces ShapeStream. Insert a Serial() boundary that
			// reads from f.Input and produces a new var.
			serialVar := f.Input + "Serial"
			boundary := &CodeFragment{
				Type:    "stmt",
				Var:     serialVar,
				Input:   f.Input,
				Code:    serialVar + " := " + f.Input + ".Serial()",
				Imports: []string{"github.com/rosscartlidge/ssql/v4/typed"},
				// Carry the upstream's typed schema through.
				InputTypedSchema:  f.InputTypedSchema,
				OutputTypedSchema: f.InputTypedSchema,
				Capabilities: &Capabilities{
					Accepts:  ShapeStream,
					Produces: ShapeSeqTyped,
				},
			}
			out = append(out, boundary)
			// Rewrite the SerialOnly fragment's code/input to consume
			// the serialised var instead of the original Stream var.
			// Word-boundary regex so we don't mangle identifiers
			// that contain the input name as a substring (e.g. if
			// the input is "records" we mustn't replace inside
			// "recordsSerial" itself).
			rewritten := *f
			rewritten.Code = replaceIdentifier(f.Code, f.Input, serialVar)
			rewritten.Input = serialVar
			out = append(out, &rewritten)
			continue
		}
		out = append(out, f)
	}
	return out
}

// replaceIdentifier replaces all word-boundary occurrences of `old` in
// `s` with `new`. Used by applyPlannerBoundaries to rewrite
// references to the upstream variable when inserting a Serial()
// boundary, without mangling identifiers that contain `old` as a
// substring (e.g. when old="records" we mustn't touch
// "recordsSerial" — both halves of the boundary share the prefix).
func replaceIdentifier(s, old, new string) string {
	if !strings.Contains(s, old) {
		return s
	}
	re := identRegexpFor(old)
	return re.ReplaceAllString(s, new)
}

var identRegexpCache = map[string]*regexp.Regexp{}

func identRegexpFor(name string) *regexp.Regexp {
	if re, ok := identRegexpCache[name]; ok {
		return re
	}
	re := regexp.MustCompile(`\b` + regexp.QuoteMeta(name) + `\b`)
	identRegexpCache[name] = re
	return re
}
