package commands

import (
	"encoding/json"
	"fmt"
	"strings"

	cf "github.com/rosscartlidge/autocli/v4"
	"github.com/rosscartlidge/ssql/v4/cmd/ssql/lib"
)

// registerGenerateJSON registers `generate json`: the pipeline as a document
// for `ssql run` (DFC134 §5.1/§5.5). The source is each fragment's Op.Argv,
// the emitting process's own argv, so no shell text is ever parsed; a
// process-substitution source (a func fragment) becomes a nested pipeline in
// the argument that named its /dev/fd. `run -print` is the other direction,
// so text → document → text round-trips.
func registerGenerateJSON(cmd *cf.SubcommandBuilder) {
	cmd.Subcommand("json").
		Description("Emit the pipeline as a document for `ssql run`: a JSON list of stages, each the stage's own argv").
		Example("(export SSQL_MODE=record; ssql from data.csv | ssql where -if age gt 25 | ssql to csv) | ssql generate json > pipeline.json", "Capture a typed pipeline as a document").
		Example("ssql run pipeline.json", "Run it later, with no shell").
		Example("(export SSQL_MODE=record; ssql from a.csv | ssql join <(ssql from b.csv) -using id | ssql to csv) | ssql generate json", "A process substitution becomes a nested pipeline").

		Flag("-compact").
			Bool().
			Global().
			Help("The whole document on one line").
			Done().

		Handler(func(ctx *cf.Context) error {
			fragments, err := lib.ReadCodeFragmentsFromReader(ctx.Stdin())
			if err != nil {
				return fmt.Errorf("reading fragments: %w", err)
			}
			doc, err := pipelineDocFromFragments(fragments)
			if err != nil {
				return err
			}
			if ctx.GetBool("-compact", false) {
				out, err := json.Marshal(doc)
				if err != nil {
					return err
				}
				fmt.Fprintln(ctx.Stdout(), string(out))
				return nil
			}
			// One stage per line: the shape of the pipeline is visible and
			// a diff between two documents is a diff between stages.
			w := ctx.Stdout()
			fmt.Fprintln(w, "[")
			for i, stage := range doc {
				line, err := json.Marshal(stage)
				if err != nil {
					return err
				}
				sep := ","
				if i == len(doc)-1 {
					sep = ""
				}
				fmt.Fprintf(w, "  %s%s\n", line, sep)
			}
			fmt.Fprintln(w, "]")
			return nil
		}).
		Done()
}

// pipelineDocFromFragments builds the document: stage fragments in order,
// each from its Op.Argv; a func fragment (emitted just before the stage
// that reads it, in argument order) replaces that stage's matching /dev/fd
// argument with the nested pipeline of its body. Continuation fragments
// (Command == "", e.g. group-by's second) are not stages. A fragment
// without an Op comes from an older ssql across an SSH boundary; the
// command string is shell text and is not parsed here.
func pipelineDocFromFragments(fragments []*lib.CodeFragment) ([]any, error) {
	var doc []any
	var pending []*lib.CodeFragment // func fragments awaiting their consumer
	for _, frag := range fragments {
		if frag.Type == "error" {
			return nil, fmt.Errorf("pipeline stage failed to generate: %s", strings.TrimSpace(frag.Code))
		}
		if frag.Type == "func" {
			pending = append(pending, frag)
			continue
		}
		if frag.Command == "" {
			continue
		}
		if frag.Op == nil || frag.Op.Kind == "" {
			return nil, fmt.Errorf("stage %q carries no argv (generated by an older ssql?); generate json needs the emitting process's own arguments", frag.Command)
		}
		stage := []any{frag.Op.Kind}
		pi := 0
		for _, a := range frag.Op.Argv {
			if strings.HasPrefix(a, "/dev/fd/") && pi < len(pending) {
				nested, err := pipelineDocFromFragments(pending[pi].FuncBody)
				if err != nil {
					return nil, fmt.Errorf("nested pipeline %q: %w", pending[pi].Command, err)
				}
				stage = append(stage, nested)
				pi++
				continue
			}
			stage = append(stage, a)
		}
		// A func fragment the argv does not reference by /dev/fd was the
		// stage's own way of reading a file it names directly (`join
		// customers.csv` emits one for the CSV); the argv already says
		// what to read, so the document keeps the file name.
		pending = nil
		doc = append(doc, stage)
	}
	if len(pending) > 0 {
		return nil, fmt.Errorf("%d process-substitution source(s) with no consuming stage", len(pending))
	}
	if len(doc) == 0 {
		return nil, fmt.Errorf("no pipeline stages received on stdin — run the pipeline with SSQL_MODE=record and pipe it here")
	}
	return doc, nil
}
