package typed

import (
	"fmt"
	"sync"
)

// ReadError is the fail-fast error of the typed readers: a value that
// does not fit its struct field's type, a short or malformed row, a
// line the JSON decoder rejects, an unreadable file. The lossy readers
// (ReadCSV, ReadCSVParallel, ReadDelim, ReadDelimParallel, ReadJSONL,
// ReadJSONLParallel and their FromReader forms) PANIC with a
// *ReadError; the *Safe readers yield it as their error value.
//
// Why panic: an iter.Seq[T] has no error channel, and the alternatives
// were tried and found dangerous — before v4.91.0 the CSV readers kept
// a row whose bad cell had been zeroed (a "1.5" in an int64 column
// became 0, silently — DFC124 §3's signal-became-zeros bug, in the
// typed lane), the JSONL readers dropped the row, and a missing file
// was an empty stream with exit status 0. The root package's
// ssql.ReadCSV has the same contract (panic *ssql.CellError), and a
// program generated by `ssql generate go` recovers either into
// "Error: …" and exit status 1. Library callers who want per-row
// recovery use the *Safe readers.
//
// Row is the 1-based data row for CSV/delimited input (the header is
// not counted); Line is the 1-based physical line for JSONL input.
// Both are 0 when the error is not row-specific (open, header).
type ReadError struct {
	Op     string // the reader: "typed.ReadCSV", "typed.ReadJSONLParallel", …
	Source string // file name; "" when reading an io.Reader
	Row    int64  // CSV/Delim: 1-based data row, 0 = not row-specific
	Line   int64  // JSONL: 1-based physical line, 0 = not line-specific
	Err    error
}

func (e *ReadError) Error() string {
	where := e.Op
	if e.Source != "" {
		where += " " + e.Source
	}
	switch {
	case e.Row > 0:
		return fmt.Sprintf("%s: row %d: %v", where, e.Row, e.Err)
	case e.Line > 0:
		return fmt.Sprintf("%s: line %d: %v", where, e.Line, e.Err)
	}
	return fmt.Sprintf("%s: %v", where, e.Err)
}

func (e *ReadError) Unwrap() error { return e.Err }

// failRead is the lossy readers' single exit for a fatal condition.
func failRead(op, source string, err error) {
	panic(&ReadError{Op: op, Source: source, Err: err})
}

func failRow(op, source string, row int64, err error) {
	panic(&ReadError{Op: op, Source: source, Row: row, Err: err})
}

func failLine(op, source string, line int64, err error) {
	panic(&ReadError{Op: op, Source: source, Line: line, Err: err})
}

// shardGroup runs shard bodies in goroutines and re-raises the FIRST
// panic in the goroutine that calls Wait. Without it a reader's
// fail-fast *ReadError inside a worker tears the process down from
// that goroutine with a stack trace (exit status 2), bypassing the
// caller's recover — the generated program's main never gets to print
// "Error: …". Every Stream consumer that fans out (Serial, SerialCount,
// GroupByParallel, the per-shard sinks, top-k, distinct) runs its
// workers through this.
type shardGroup struct {
	wg    sync.WaitGroup
	mu    sync.Mutex
	panic any
}

// Go runs fn in a new goroutine, capturing a panic instead of crashing.
func (g *shardGroup) Go(fn func()) {
	g.wg.Add(1)
	go func() {
		defer g.wg.Done()
		defer func() {
			if r := recover(); r != nil {
				g.mu.Lock()
				if g.panic == nil {
					g.panic = r
				}
				g.mu.Unlock()
			}
		}()
		fn()
	}()
}

// Wait blocks until every goroutine has finished, then re-raises the
// first captured panic (if any) in the caller's goroutine.
func (g *shardGroup) Wait() {
	g.wg.Wait()
	g.rethrow()
}

// waitQuiet blocks without re-raising; rethrow must follow in the
// goroutine that should receive the panic (Serial's fan-in closer
// waits in one goroutine while the consumer loop is in another).
func (g *shardGroup) waitQuiet() { g.wg.Wait() }

func (g *shardGroup) rethrow() {
	g.mu.Lock()
	r := g.panic
	g.mu.Unlock()
	if r != nil {
		panic(r)
	}
}
