#!/usr/bin/env python3
"""DFC (Doc For Comment) metadata tool for doc/research/*.md.

Every research doc carries a metadata block right below its # Title:

    Reference: DFC042
    Created: 2026-05-14
    Last modified: 2026-08-11

    [Back to Index](./README.md)

Numbers are assigned once (chronologically by git creation date at
backfill; max+1 afterwards) and NEVER change — they are stable handles
for journals, commit messages, and cross-doc references. Filenames of
NEW docs should be dfcnnn_description.md; pre-DFC files keep their
original names (renaming would break inbound links).

Usage:
    scripts/dfc.py --stamp   # insert missing blocks, sync dates from git
    scripts/dfc.py --index   # regenerate the DFC table in README.md
    scripts/dfc.py --check   # validate (used by make doc-check); exit 1 on problems
    scripts/dfc.py --new     # print the next free DFC number
"""

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCDIR = ROOT / "doc" / "research"
README = DOCDIR / "README.md"
INDEX_START = "<!-- DFC-INDEX-START (generated by scripts/dfc.py --index; do not edit by hand) -->"
INDEX_END = "<!-- DFC-INDEX-END -->"

REF_RE = re.compile(r"^Reference:\s*DFC(\d{3})\s*$", re.M)
CREATED_RE = re.compile(r"^Created:\s*(\d{4}-\d{2}-\d{2})\s*$", re.M)
MODIFIED_RE = re.compile(r"^Last modified:\s*(\d{4}-\d{2}-\d{2})\s*$", re.M)
BACK_LINK = "[Back to Index](./README.md)"


def docs():
    return sorted(p for p in DOCDIR.glob("*.md") if p.name != "README.md")


def git_dates(path):
    """(created, last_modified) as YYYY-MM-DD from git; today if untracked."""
    rel = path.relative_to(ROOT)
    out = subprocess.run(
        ["git", "log", "--follow", "--format=%as", "--", str(rel)],
        cwd=ROOT, capture_output=True, text=True,
    ).stdout.split()
    today = datetime.date.today().isoformat()
    if not out:
        return today, today
    return out[-1], out[0]


def parse_meta(text):
    ref = REF_RE.search(text)
    created = CREATED_RE.search(text)
    modified = MODIFIED_RE.search(text)
    return (
        int(ref.group(1)) if ref else None,
        created.group(1) if created else None,
        modified.group(1) if modified else None,
    )


def title_of(text, path):
    m = re.search(r"^#\s+(.+)$", text, re.M)
    return m.group(1).strip() if m else path.stem


def uncommitted(path):
    rel = str(path.relative_to(ROOT))
    out = subprocess.run(["git", "status", "--porcelain", "--", rel],
                         cwd=ROOT, capture_output=True, text=True).stdout
    return bool(out.strip())


def stamp():
    """Insert missing metadata blocks; sync Last modified from git state.
    Never renumbers an existing Reference."""
    entries = []
    for p in docs():
        text = p.read_text()
        ref, created_hdr, _ = parse_meta(text)
        created_git, modified_git = git_dates(p)
        entries.append([p, text, ref, created_hdr or created_git, modified_git])

    used = {e[2] for e in entries if e[2] is not None}
    # Assign numbers to unnumbered docs chronologically (created, name).
    next_no = max(used, default=0) + 1
    for e in sorted((e for e in entries if e[2] is None), key=lambda e: (e[3], e[0].name)):
        e[2] = next_no
        used.add(next_no)
        next_no += 1

    changed = 0
    for p, text, ref, created, modified_git in entries:
        # An uncommitted edit is "modified today" — stamp before committing.
        modified = datetime.date.today().isoformat() if uncommitted(p) else modified_git
        block = (f"Reference: DFC{ref:03d}\nCreated: {created}\n"
                 f"Last modified: {modified}\n\n{BACK_LINK}\n")
        if REF_RE.search(text):
            new = MODIFIED_RE.sub(f"Last modified: {modified}", text)
            new = CREATED_RE.sub(f"Created: {created}", new)
        else:
            m = re.search(r"^#\s+.+$", text, re.M)
            if not m:
                new = block + "\n" + text
            else:
                at = m.end()  # block goes: title, blank, block, blank, rest
                new = text[:at] + "\n\n" + block + "\n" + text[at:].lstrip("\n")
        if new != text:
            p.write_text(new)
            changed += 1
    print(f"stamped {changed} of {len(entries)} docs")


def build_index_lines():
    rows = []
    for p in docs():
        text = p.read_text()
        ref, created, modified = parse_meta(text)
        if ref is None:
            continue
        rows.append((ref, created or "?", modified or "?", p.name, title_of(text, p)))
    rows.sort()
    lines = ["", "| DFC | Created | Modified | Document |", "|---|---|---|---|"]
    for ref, created, modified, name, title in rows:
        lines.append(f"| DFC{ref:03d} | {created} | {modified} | [{title}](./{name}) |")
    lines.append("")
    return lines


def splice_index(text):
    lines = build_index_lines()
    region = INDEX_START + "\n" + "\n".join(lines) + "\n" + INDEX_END
    if INDEX_START in text:
        return re.sub(re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END),
                      region, text, flags=re.S)
    # First insertion: after the intro paragraph (before the first ## section).
    m = re.search(r"^##\s", text, re.M)
    at = m.start() if m else len(text)
    return text[:at] + "## Chronological Index (DFC)\n\n" + region + "\n\n" + text[at:]


def index():
    README.write_text(splice_index(README.read_text()))
    print("index regenerated")


def check():
    problems = []
    seen = {}
    readme_text = README.read_text()
    for p in docs():
        text = p.read_text()
        ref, created, modified = parse_meta(text)
        if ref is None or created is None or modified is None:
            problems.append(f"{p.name}: missing DFC metadata block (run scripts/dfc.py --stamp)")
            continue
        if BACK_LINK not in text:
            problems.append(f"{p.name}: missing '{BACK_LINK}' link")
        if ref in seen:
            problems.append(f"{p.name}: duplicate reference DFC{ref:03d} (also {seen[ref]})")
        seen[ref] = p.name
        _, modified_git = git_dates(p)
        if not uncommitted(p) and modified < modified_git:
            problems.append(f"{p.name}: Last modified {modified} older than last commit "
                            f"{modified_git} (run scripts/dfc.py --stamp)")
        if f"DFC{ref:03d}" not in readme_text:
            problems.append(f"{p.name}: DFC{ref:03d} not in README index (run scripts/dfc.py --index)")
    if splice_index(readme_text) != readme_text:
        problems.append("README.md: DFC index region out of date (run scripts/dfc.py --index)")
    for pr in problems:
        print("DFC: " + pr)
    if problems:
        sys.exit(1)
    print(f"DFC: {len(seen)} docs OK")


def new():
    used = [parse_meta(p.read_text())[0] for p in docs()]
    n = max((u for u in used if u), default=0) + 1
    print(f"DFC{n:03d}  (filename: dfc{n:03d}_short_description.md)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stamp", action="store_true")
    ap.add_argument("--index", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--new", action="store_true")
    a = ap.parse_args()
    if a.stamp:
        stamp()
    if a.index:
        index()
    if a.check:
        check()
    if a.new:
        new()
    if not (a.stamp or a.index or a.check or a.new):
        ap.print_help()


if __name__ == "__main__":
    main()
